services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t frebib/certbot-cron . 

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push frebib/certbot-cron

